// <auto-generated />
using System;
using Bikeapelago.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bikeapelago.Api.Migrations
{
    [DbContext(typeof(BikeapelagoDbContext))]
    [Migration("20260408024033_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bikeapelago.Api.Models.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasJsonPropertyName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasJsonPropertyName("name");

                    b.Property<LineString>("Path")
                        .HasColumnType("geometry (linestring)");

                    b.Property<string>("Sport")
                        .HasColumnType("text")
                        .HasJsonPropertyName("sport");

                    b.Property<string>("StartTime")
                        .HasColumnType("text")
                        .HasJsonPropertyName("start_time");

                    b.Property<double?>("TotDistance")
                        .HasColumnType("double precision")
                        .HasJsonPropertyName("tot_distance");

                    b.Property<double?>("TotElevation")
                        .HasColumnType("double precision")
                        .HasJsonPropertyName("tot_elevation");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("user");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("Bikeapelago.Api.Models.ApiLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ExceptionType")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("QueryString")
                        .HasColumnType("text");

                    b.Property<string>("RequestBody")
                        .HasColumnType("text");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ApiLogs");
                });

            modelBuilder.Entity("Bikeapelago.Api.Models.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("id");

                    b.Property<string>("ApSeedName")
                        .HasColumnType("text")
                        .HasJsonPropertyName("ap_seed_name");

                    b.Property<string>("ApServerUrl")
                        .HasColumnType("text")
                        .HasJsonPropertyName("ap_server_url");

                    b.Property<string>("ApSlotName")
                        .HasColumnType("text")
                        .HasJsonPropertyName("ap_slot_name");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("created");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry (point)");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasJsonPropertyName("name");

                    b.Property<int?>("Radius")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("radius");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("status");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("updated");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("user");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("Bikeapelago.Api.Models.MapNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("id");

                    b.Property<long>("ApLocationId")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("ap_location_id");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry (point)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("name");

                    b.Property<string>("OsmNodeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("osm_node_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("session");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("state");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("MapNodes");
                });

            modelBuilder.Entity("Bikeapelago.Api.Models.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("id");

                    b.Property<double?>("Distance")
                        .HasColumnType("double precision")
                        .HasJsonPropertyName("distance");

                    b.Property<double?>("Elevation")
                        .HasColumnType("double precision")
                        .HasJsonPropertyName("elevation");

                    b.Property<LineString>("Path")
                        .HasColumnType("geometry (linestring)");

                    b.Property<string>("Sport")
                        .HasColumnType("text")
                        .HasJsonPropertyName("sport");

                    b.Property<double?>("Time")
                        .HasColumnType("double precision")
                        .HasJsonPropertyName("time");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasJsonPropertyName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("user");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("Bikeapelago.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("id");

                    b.Property<string>("Avatar")
                        .HasColumnType("text")
                        .HasJsonPropertyName("avatar");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasJsonPropertyName("email");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasJsonPropertyName("name");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("username");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision")
                        .HasJsonPropertyName("weight");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Bikeapelago.Api.Models.Activity", b =>
                {
                    b.HasOne("Bikeapelago.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bikeapelago.Api.Models.GameSession", b =>
                {
                    b.HasOne("Bikeapelago.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bikeapelago.Api.Models.MapNode", b =>
                {
                    b.HasOne("Bikeapelago.Api.Models.GameSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bikeapelago.Api.Models.Route", b =>
                {
                    b.HasOne("Bikeapelago.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
