using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

namespace Bikeapelago.Api.Tests.Integration;

/// <summary>
/// Validates that nodes generated by PostGIS are snappable to the correct road network
/// by auditing each coordinate against GraphHopper's /nearest endpoint.
///
/// A large snap delta (50m+) means PostGIS returned a node on an invalid road type
/// (e.g. motorway, footway) for the requested mode, and GraphHopper had to seek
/// the nearest valid road elsewhere.
///
/// Requires live Docker stack. Set env vars to override defaults:
///   BIKEAPELAGO_API_URL  (default: http://bikeapelago-api.orb.local)
///   BIKEAPELAGO_TOKEN
///   GRAPHHOPPER_URL      (default: http://localhost:8990)
/// </summary>
[Trait("Category", "Integration")]
public class GraphHopperNodeValidationTests : IAsyncLifetime
{
    private static readonly string ApiBase =
        Environment.GetEnvironmentVariable("BIKEAPELAGO_API_URL")
        ?? "http://bikeapelago-api.orb.local";

    private static readonly string GraphHopperBase =
        Environment.GetEnvironmentVariable("GRAPHHOPPER_URL")
        ?? "http://localhost:8990";

    private static readonly string Token =
        Environment.GetEnvironmentVariable("BIKEAPELAGO_TOKEN")
        ?? "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjAxOWQ2ZGM0LTQ5NjUtNzhmZi05ZjJhLWYyN2IyMWFmZDNlNiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJha2libGVyMTZAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoiYWtpYmxlcjE2QGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzc2MzQyNjkyLCJpc3MiOiJiaWtlYXBlbGFnby1hcGkiLCJhdWQiOiJiaWtlYXBlbGFnby1mcm9udGVuZCJ9.aq_Hc147_Oy1RzhH2dZ0ZlxPpCVMTxvJgqJgqTYQTx0";

    private static readonly string UserId = "019d6dc4-4965-78ff-9f2a-f27b21afd3e6";

    // Pass threshold: nodes snapping further than this are on the wrong road type
    private const double MaxSnapMeters = 20.0;
    // Nodes snapping this far are definitely wrong — logged as hard failures
    private const double HardFailMeters = 50.0;

    // Cities spread across North America for coverage breadth
    public record City(string Name, double Lat, double Lon);

    private static readonly City[] NaCities =
    [
        // Northeast US
        new("Pittsburgh, PA",     40.4406, -79.9959),
        new("New York, NY",       40.7128, -74.0060),
        new("Boston, MA",         42.3601, -71.0589),
        new("Washington DC",      38.9072, -77.0369),
        new("Philadelphia, PA",   39.9526, -75.1652),
        // Midwest
        new("Chicago, IL",        41.8781, -87.6298),
        new("Minneapolis, MN",    44.9778, -93.2650),
        new("Detroit, MI",        42.3314, -83.0458),
        new("Columbus, OH",       39.9612, -82.9988),
        new("Milwaukee, WI",      43.0389, -87.9065),
        // South
        new("Atlanta, GA",        33.7490, -84.3880),
        new("Nashville, TN",      36.1627, -86.7816),
        new("Austin, TX",         30.2672, -97.7431),
        new("Dallas, TX",         32.7767, -96.7970),
        new("Houston, TX",        29.7604, -95.3698),
        new("Miami, FL",          25.7617, -80.1918),
        new("Charlotte, NC",      35.2271, -80.8431),
        new("New Orleans, LA",    29.9511, -90.0715),
        // Mountain / West
        new("Denver, CO",         39.7392, -104.9903),
        new("Salt Lake City, UT", 40.7608, -111.8910),
        new("Phoenix, AZ",        33.4484, -112.0740),
        new("Albuquerque, NM",    35.0844, -106.6504),
        new("Boise, ID",          43.6150, -116.2023),
        new("Las Vegas, NV",      36.1699, -115.1398),
        // Pacific
        new("Seattle, WA",        47.6062, -122.3321),
        new("Portland, OR",       45.5051, -122.6750),
        new("San Francisco, CA",  37.7749, -122.4194),
        new("Los Angeles, CA",    34.0522, -118.2437),
        new("San Diego, CA",      32.7157, -117.1611),
        new("Sacramento, CA",     38.5816, -121.4944),
        // Canada
        new("Vancouver, BC",      49.2827, -123.1207),
        new("Calgary, AB",        51.0447, -114.0719),
        new("Edmonton, AB",       53.5461, -113.4938),
        new("Toronto, ON",        43.6510, -79.3470),
        new("Ottawa, ON",         45.4215, -75.6972),
        new("Montreal, QC",       45.5017, -73.5673),
        new("Winnipeg, MB",       49.8954, -97.1385),
    ];

    public static IEnumerable<object[]> AllCities() =>
        NaCities.Select(c => new object[] { c });

    // Subset of dense urban cities for stress tests
    public static IEnumerable<object[]> DenseUrbanCities() =>
        NaCities
            .Where(c => c.Name is "New York, NY" or "Chicago, IL" or "Los Angeles, CA"
                              or "San Francisco, CA" or "Washington DC" or "Boston, MA"
                              or "Toronto, ON" or "Vancouver, BC")
            .Select(c => new object[] { c });

    // Smaller/mid-size cities for suburban/less-dense coverage
    public static IEnumerable<object[]> SuburbanCities() =>
        NaCities
            .Where(c => c.Name is "Boise, ID" or "Columbus, OH" or "Albuquerque, NM"
                              or "Salt Lake City, UT" or "Ottawa, ON" or "Winnipeg, MB"
                              or "Charlotte, NC" or "Milwaukee, WI")
            .Select(c => new object[] { c });

    private readonly HttpClient _apiClient;
    private readonly HttpClient _ghClient;
    private readonly List<Guid> _createdSessionIds = [];

    public GraphHopperNodeValidationTests()
    {
        _apiClient = new HttpClient { BaseAddress = new Uri(ApiBase) };
        _apiClient.DefaultRequestHeaders.Authorization =
            new AuthenticationHeaderValue("Bearer", Token);
        _apiClient.Timeout = TimeSpan.FromMinutes(5);

        _ghClient = new HttpClient { BaseAddress = new Uri(GraphHopperBase) };
        _ghClient.Timeout = TimeSpan.FromSeconds(15);
    }

    public Task InitializeAsync() => Task.CompletedTask;

    public async Task DisposeAsync()
    {
        foreach (var id in _createdSessionIds)
        {
            try { await _apiClient.DeleteAsync($"/api/sessions/{id}"); }
            catch { /* best-effort */ }
        }
        _apiClient.Dispose();
        _ghClient.Dispose();
    }

    // ── Original Pittsburgh tests (kept for regression) ───────────────────

    [Fact]
    public async Task BikeNodes_Pittsburgh_SnapWithin20m_OfValidCycleRoute()
    {
        var city = new City("Pittsburgh, PA", 40.4406, -79.9959);
        var nodes = await GenerateNodes(city, mode: "bike", nodeCount: 500, radiusMeters: 50_000);
        var results = await AuditWithGraphHopper(nodes, vehicle: "bike");
        AssertSnapResults(results, $"bike/{city.Name}");
    }

    [Fact]
    public async Task WalkNodes_Pittsburgh_SnapWithin20m_OfValidFootpath()
    {
        var city = new City("Pittsburgh, PA", 40.4406, -79.9959);
        var nodes = await GenerateNodes(city, mode: "walk", nodeCount: 500, radiusMeters: 50_000);
        var results = await AuditWithGraphHopper(nodes, vehicle: "foot");
        AssertSnapResults(results, $"walk/{city.Name}");
    }

    // ── Multi-city sweep: standard scale ─────────────────────────────────

    [Theory]
    [MemberData(nameof(AllCities))]
    public async Task BikeNodes_AllCities_StandardRadius_SnapWithin20m(City city)
    {
        var nodes = await GenerateNodes(city, mode: "bike", nodeCount: 100, radiusMeters: 20_000);
        var results = await AuditWithGraphHopper(nodes, vehicle: "bike");
        AssertSnapResults(results, $"bike/{city.Name}");
    }

    [Theory]
    [MemberData(nameof(AllCities))]
    public async Task WalkNodes_AllCities_StandardRadius_SnapWithin20m(City city)
    {
        var nodes = await GenerateNodes(city, mode: "walk", nodeCount: 100, radiusMeters: 20_000);
        var results = await AuditWithGraphHopper(nodes, vehicle: "foot");
        AssertSnapResults(results, $"walk/{city.Name}");
    }

    // ── Multi-city sweep: small neighborhood radius ───────────────────────

    [Theory]
    [MemberData(nameof(AllCities))]
    public async Task BikeNodes_AllCities_SmallRadius_SnapWithin20m(City city)
    {
        var nodes = await GenerateNodes(city, mode: "bike", nodeCount: 50, radiusMeters: 3_000);
        var results = await AuditWithGraphHopper(nodes, vehicle: "bike");
        AssertSnapResults(results, $"bike-small/{city.Name}");
    }

    [Theory]
    [MemberData(nameof(AllCities))]
    public async Task WalkNodes_AllCities_SmallRadius_SnapWithin20m(City city)
    {
        var nodes = await GenerateNodes(city, mode: "walk", nodeCount: 50, radiusMeters: 3_000);
        var results = await AuditWithGraphHopper(nodes, vehicle: "foot");
        AssertSnapResults(results, $"walk-small/{city.Name}");
    }

    // ── Multi-city sweep: large metro radius ─────────────────────────────

    [Theory]
    [MemberData(nameof(AllCities))]
    public async Task BikeNodes_AllCities_LargeRadius_SnapWithin20m(City city)
    {
        var nodes = await GenerateNodes(city, mode: "bike", nodeCount: 200, radiusMeters: 75_000);
        var results = await AuditWithGraphHopper(nodes, vehicle: "bike");
        AssertSnapResults(results, $"bike-large/{city.Name}");
    }

    [Theory]
    [MemberData(nameof(AllCities))]
    public async Task WalkNodes_AllCities_LargeRadius_SnapWithin20m(City city)
    {
        var nodes = await GenerateNodes(city, mode: "walk", nodeCount: 200, radiusMeters: 75_000);
        var results = await AuditWithGraphHopper(nodes, vehicle: "foot");
        AssertSnapResults(results, $"walk-large/{city.Name}");
    }

    // ── Node count scaling tests (Pittsburgh as baseline) ────────────────

    [Fact]
    public async Task BikeNodes_Scale_50Nodes_Pittsburgh()
    {
        var city = new City("Pittsburgh, PA", 40.4406, -79.9959);
        var nodes = await GenerateNodes(city, mode: "bike", nodeCount: 50, radiusMeters: 20_000);
        var results = await AuditWithGraphHopper(nodes, vehicle: "bike");
        AssertSnapResults(results, "bike/scale-50");
    }

    [Fact]
    public async Task BikeNodes_Scale_250Nodes_Pittsburgh()
    {
        var city = new City("Pittsburgh, PA", 40.4406, -79.9959);
        var nodes = await GenerateNodes(city, mode: "bike", nodeCount: 250, radiusMeters: 30_000);
        var results = await AuditWithGraphHopper(nodes, vehicle: "bike");
        AssertSnapResults(results, "bike/scale-250");
    }

    [Fact]
    public async Task BikeNodes_Scale_1000Nodes_Pittsburgh()
    {
        var city = new City("Pittsburgh, PA", 40.4406, -79.9959);
        var nodes = await GenerateNodes(city, mode: "bike", nodeCount: 1000, radiusMeters: 75_000);
        var results = await AuditWithGraphHopper(nodes, vehicle: "bike");
        AssertSnapResults(results, "bike/scale-1000");
    }

    [Fact]
    public async Task WalkNodes_Scale_1000Nodes_Pittsburgh()
    {
        var city = new City("Pittsburgh, PA", 40.4406, -79.9959);
        var nodes = await GenerateNodes(city, mode: "walk", nodeCount: 1000, radiusMeters: 75_000);
        var results = await AuditWithGraphHopper(nodes, vehicle: "foot");
        AssertSnapResults(results, "walk/scale-1000");
    }

    // ── Dense urban stress tests ──────────────────────────────────────────

    [Theory]
    [MemberData(nameof(DenseUrbanCities))]
    public async Task BikeNodes_DenseUrban_HighCount_SnapWithin20m(City city)
    {
        var nodes = await GenerateNodes(city, mode: "bike", nodeCount: 500, radiusMeters: 50_000);
        var results = await AuditWithGraphHopper(nodes, vehicle: "bike");
        AssertSnapResults(results, $"bike-dense/{city.Name}");
    }

    [Theory]
    [MemberData(nameof(DenseUrbanCities))]
    public async Task WalkNodes_DenseUrban_HighCount_SnapWithin20m(City city)
    {
        var nodes = await GenerateNodes(city, mode: "walk", nodeCount: 500, radiusMeters: 50_000);
        var results = await AuditWithGraphHopper(nodes, vehicle: "foot");
        AssertSnapResults(results, $"walk-dense/{city.Name}");
    }

    // ── Suburban/mid-size city tests ──────────────────────────────────────

    [Theory]
    [MemberData(nameof(SuburbanCities))]
    public async Task BikeNodes_Suburban_SnapWithin20m(City city)
    {
        var nodes = await GenerateNodes(city, mode: "bike", nodeCount: 200, radiusMeters: 30_000);
        var results = await AuditWithGraphHopper(nodes, vehicle: "bike");
        AssertSnapResults(results, $"bike-suburban/{city.Name}");
    }

    [Theory]
    [MemberData(nameof(SuburbanCities))]
    public async Task WalkNodes_Suburban_SnapWithin20m(City city)
    {
        var nodes = await GenerateNodes(city, mode: "walk", nodeCount: 200, radiusMeters: 30_000);
        var results = await AuditWithGraphHopper(nodes, vehicle: "foot");
        AssertSnapResults(results, $"walk-suburban/{city.Name}");
    }

    // ── Canada-specific coverage ──────────────────────────────────────────

    [Theory]
    [MemberData(nameof(CanadianCities))]
    public async Task BikeNodes_Canada_SnapWithin20m(City city)
    {
        var nodes = await GenerateNodes(city, mode: "bike", nodeCount: 200, radiusMeters: 30_000);
        var results = await AuditWithGraphHopper(nodes, vehicle: "bike");
        AssertSnapResults(results, $"bike-canada/{city.Name}");
    }

    [Theory]
    [MemberData(nameof(CanadianCities))]
    public async Task WalkNodes_Canada_SnapWithin20m(City city)
    {
        var nodes = await GenerateNodes(city, mode: "walk", nodeCount: 200, radiusMeters: 30_000);
        var results = await AuditWithGraphHopper(nodes, vehicle: "foot");
        AssertSnapResults(results, $"walk-canada/{city.Name}");
    }

    public static IEnumerable<object[]> CanadianCities() =>
        NaCities
            .Where(c => c.Name.EndsWith(", BC") || c.Name.EndsWith(", AB")
                     || c.Name.EndsWith(", ON") || c.Name.EndsWith(", QC")
                     || c.Name.EndsWith(", MB"))
            .Select(c => new object[] { c });

    // ── Cross-mode consistency: same city, both modes independent ─────────

    [Theory]
    [MemberData(nameof(DenseUrbanCities))]
    public async Task BikeAndWalk_DenseUrban_BothPassIndependently(City city)
    {
        var bikeNodes = await GenerateNodes(city, mode: "bike", nodeCount: 100, radiusMeters: 20_000);
        var walkNodes = await GenerateNodes(city, mode: "walk", nodeCount: 100, radiusMeters: 20_000);

        var bikeResults = await AuditWithGraphHopper(bikeNodes, vehicle: "bike");
        var walkResults = await AuditWithGraphHopper(walkNodes, vehicle: "foot");

        AssertSnapResults(bikeResults, $"bike-xmode/{city.Name}");
        AssertSnapResults(walkResults, $"walk-xmode/{city.Name}");
    }

    // ── Radius boundary tests ─────────────────────────────────────────────

    [Fact]
    public async Task BikeNodes_VerySmallRadius_1km_SnapWithin20m()
    {
        var city = new City("Chicago, IL", 41.8781, -87.6298);
        var nodes = await GenerateNodes(city, mode: "bike", nodeCount: 20, radiusMeters: 1_000);
        var results = await AuditWithGraphHopper(nodes, vehicle: "bike");
        AssertSnapResults(results, "bike/radius-1km");
    }

    [Fact]
    public async Task BikeNodes_VeryLargeRadius_150km_SnapWithin20m()
    {
        var city = new City("Denver, CO", 39.7392, -104.9903);
        var nodes = await GenerateNodes(city, mode: "bike", nodeCount: 200, radiusMeters: 150_000);
        var results = await AuditWithGraphHopper(nodes, vehicle: "bike");
        AssertSnapResults(results, "bike/radius-150km");
    }

    [Fact]
    public async Task WalkNodes_VeryLargeRadius_150km_SnapWithin20m()
    {
        var city = new City("Denver, CO", 39.7392, -104.9903);
        var nodes = await GenerateNodes(city, mode: "walk", nodeCount: 200, radiusMeters: 150_000);
        var results = await AuditWithGraphHopper(nodes, vehicle: "foot");
        AssertSnapResults(results, "walk/radius-150km");
    }

    // ── Coastal / geographic edge cases ───────────────────────────────────

    [Fact]
    public async Task BikeNodes_Coastal_Miami_SnapWithin20m()
    {
        var city = new City("Miami, FL", 25.7617, -80.1918);
        var nodes = await GenerateNodes(city, mode: "bike", nodeCount: 200, radiusMeters: 30_000);
        var results = await AuditWithGraphHopper(nodes, vehicle: "bike");
        AssertSnapResults(results, "bike/coastal-miami");
    }

    [Fact]
    public async Task BikeNodes_Coastal_SanFrancisco_SnapWithin20m()
    {
        var city = new City("San Francisco, CA", 37.7749, -122.4194);
        var nodes = await GenerateNodes(city, mode: "bike", nodeCount: 200, radiusMeters: 20_000);
        var results = await AuditWithGraphHopper(nodes, vehicle: "bike");
        AssertSnapResults(results, "bike/coastal-sf");
    }

    [Fact]
    public async Task BikeNodes_Coastal_Seattle_SnapWithin20m()
    {
        var city = new City("Seattle, WA", 47.6062, -122.3321);
        var nodes = await GenerateNodes(city, mode: "bike", nodeCount: 200, radiusMeters: 20_000);
        var results = await AuditWithGraphHopper(nodes, vehicle: "bike");
        AssertSnapResults(results, "bike/coastal-seattle");
    }

    [Fact]
    public async Task WalkNodes_Coastal_NewOrleans_SnapWithin20m()
    {
        var city = new City("New Orleans, LA", 29.9511, -90.0715);
        var nodes = await GenerateNodes(city, mode: "walk", nodeCount: 150, radiusMeters: 15_000);
        var results = await AuditWithGraphHopper(nodes, vehicle: "foot");
        AssertSnapResults(results, "walk/coastal-neworleans");
    }

    // ── Hot-spot: Manhattan tight grid ───────────────────────────────────

    [Fact]
    public async Task BikeNodes_Manhattan_TightGrid_SnapWithin20m()
    {
        var city = new City("Manhattan, NY", 40.7831, -73.9712);
        var nodes = await GenerateNodes(city, mode: "bike", nodeCount: 500, radiusMeters: 5_000);
        var results = await AuditWithGraphHopper(nodes, vehicle: "bike");
        AssertSnapResults(results, "bike/manhattan-tight");
    }

    [Fact]
    public async Task WalkNodes_Manhattan_TightGrid_SnapWithin20m()
    {
        var city = new City("Manhattan, NY", 40.7831, -73.9712);
        var nodes = await GenerateNodes(city, mode: "walk", nodeCount: 500, radiusMeters: 5_000);
        var results = await AuditWithGraphHopper(nodes, vehicle: "foot");
        AssertSnapResults(results, "walk/manhattan-tight");
    }

    // ── Core audit logic ──────────────────────────────────────────────────

    private async Task<List<SnapResult>> AuditWithGraphHopper(
        List<NodeDto> nodes, string vehicle)
    {
        using var semaphore = new SemaphoreSlim(20, 20);

        var tasks = nodes.Select(async node =>
        {
            await semaphore.WaitAsync();
            try
            {
                var url = $"/nearest?point={node.Lat},{node.Lon}&vehicle={vehicle}&type=json";
                var resp = await _ghClient.GetAsync(url);

                if (!resp.IsSuccessStatusCode)
                    return new SnapResult(node, SnapMeters: double.MaxValue, Error: $"GH returned {(int)resp.StatusCode}");

                var body = await resp.Content.ReadAsStringAsync();
                using var doc = JsonDocument.Parse(body);
                var coords = doc.RootElement.GetProperty("coordinates");
                double snappedLon = coords[0].GetDouble();
                double snappedLat = coords[1].GetDouble();
                double snapMeters = HaversineMeters(node.Lat, node.Lon, snappedLat, snappedLon);

                return new SnapResult(node, snapMeters, Error: null);
            }
            catch (Exception ex)
            {
                return new SnapResult(node, SnapMeters: double.MaxValue, Error: ex.Message);
            }
            finally
            {
                semaphore.Release();
            }
        });

        return (await Task.WhenAll(tasks)).ToList();
    }

    private static void AssertSnapResults(List<SnapResult> results, string label)
    {
        var errors    = results.Where(r => r.Error != null).ToList();
        var hardFails = results.Where(r => r.Error == null && r.SnapMeters >= HardFailMeters).ToList();
        var softFails = results.Where(r => r.Error == null && r.SnapMeters >= MaxSnapMeters && r.SnapMeters < HardFailMeters).ToList();
        var passed    = results.Count(r => r.Error == null && r.SnapMeters < MaxSnapMeters);
        var validSnaps = results.Where(r => r.Error == null).ToList();

        foreach (var f in hardFails)
            Console.WriteLine($"[HARD FAIL {label}] ({f.Node.Lat:F5},{f.Node.Lon:F5}) snapped {f.SnapMeters:F1}m — likely wrong road type");
        foreach (var f in softFails)
            Console.WriteLine($"[SOFT FAIL {label}] ({f.Node.Lat:F5},{f.Node.Lon:F5}) snapped {f.SnapMeters:F1}m");
        foreach (var e in errors)
            Console.WriteLine($"[ERROR {label}] ({e.Node.Lat:F5},{e.Node.Lon:F5}) {e.Error}");

        double passRate = (double)passed / results.Count * 100;
        double avgSnap  = validSnaps.Count > 0 ? validSnaps.Average(r => r.SnapMeters) : 0;
        double maxSnap  = validSnaps.Count > 0 ? validSnaps.Max(r => r.SnapMeters) : 0;
        Console.WriteLine($"[{label}] {passed}/{results.Count} passed ({passRate:F1}%)  " +
                          $"soft={softFails.Count}  hard={hardFails.Count}  errors={errors.Count}  " +
                          $"avg={avgSnap:F1}m  max={maxSnap:F1}m");

        Assert.True(hardFails.Count == 0,
            $"{hardFails.Count} nodes for [{label}] snapped {HardFailMeters}m+: " +
            string.Join(", ", hardFails.Take(5).Select(f => $"({f.Node.Lat:F5},{f.Node.Lon:F5})={f.SnapMeters:F0}m")));

        Assert.True(errors.Count == 0,
            $"{errors.Count} GraphHopper calls failed for [{label}]: " +
            string.Join("; ", errors.Take(3).Select(e => e.Error)));

        Assert.True(softFails.Count == 0,
            $"{softFails.Count} nodes for [{label}] snapped between {MaxSnapMeters}–{HardFailMeters}m");
    }

    // ── Helpers ───────────────────────────────────────────────────────────

    private async Task<List<NodeDto>> GenerateNodes(
        City city, string mode, int nodeCount, double radiusMeters)
    {
        var createResp = await _apiClient.PostAsJsonAsync("/api/sessions", new
        {
            center_lat = city.Lat,
            center_lon = city.Lon,
            name = $"gh-audit-{mode}-{nodeCount}-{city.Name.Replace(", ", "-").Replace(" ", "")}",
            radius = (int)radiusMeters,
            status = "SetupInProgress",
            user = UserId
        });
        createResp.EnsureSuccessStatusCode();
        var session = await createResp.Content.ReadFromJsonAsync<SessionDto>()
            ?? throw new InvalidOperationException("Null session");
        _createdSessionIds.Add(session.Id);

        var genResp = await _apiClient.PostAsJsonAsync($"/api/sessions/{session.Id}/generate", new
        {
            centerLat = city.Lat,
            centerLon = city.Lon,
            radius = radiusMeters,
            nodeCount,
            mode
        });
        Assert.True(genResp.IsSuccessStatusCode,
            $"Generate failed [{city.Name}/{mode}]: {await genResp.Content.ReadAsStringAsync()}");

        var nodes = await _apiClient
            .GetFromJsonAsync<List<NodeDto>>($"/api/sessions/{session.Id}/nodes")
            ?? throw new InvalidOperationException("Null nodes");

        Assert.Equal(nodeCount, nodes.Count);
        return nodes;
    }

    private static double HaversineMeters(double lat1, double lon1, double lat2, double lon2)
    {
        const double R = 6_371_000;
        double dLat = (lat2 - lat1) * Math.PI / 180;
        double dLon = (lon2 - lon1) * Math.PI / 180;
        double a = Math.Sin(dLat / 2) * Math.Sin(dLat / 2)
                 + Math.Cos(lat1 * Math.PI / 180) * Math.Cos(lat2 * Math.PI / 180)
                 * Math.Sin(dLon / 2) * Math.Sin(dLon / 2);
        return R * 2 * Math.Atan2(Math.Sqrt(a), Math.Sqrt(1 - a));
    }

    private record SnapResult(NodeDto Node, double SnapMeters, string? Error);
    private record SessionDto([property: JsonPropertyName("id")] Guid Id);
    private record NodeDto(
        [property: JsonPropertyName("lat")] double Lat,
        [property: JsonPropertyName("lon")] double Lon);
}
